export type Category =
  | "chat"
  | "coding"
  | "image"
  | "video"
  | "data"
  | "notes"
  | "aggregator";

export type Pricing = "free" | "freemium" | "paid" | "api";

export type Tool = {
  id: string;
  name: string;
  vendor: string;
  url: string;
  category: Category;
  pricing: Pricing;
  /** What it is actually good at */
  bestFor: string[];
  /** Honest limits */
  notFor: string[];
  /** Curated reliability 1–5 for typical use (not a lab benchmark) */
  reliability: number;
  freeTier: boolean;
  /** Can SameAsk live-test via API when user brings a key */
  liveTestable: boolean;
  openRouterId?: string;
  notes: string;
  tags: string[];
};

export const CATEGORIES: { id: Category; label: string; blurb: string }[] = [
  { id: "chat", label: "Chat LLMs", blurb: "Talk, reason, write, research" },
  { id: "coding", label: "Coding tools", blurb: "IDE agents and code assistants" },
  { id: "image", label: "Image gen", blurb: "Still images and design" },
  { id: "video", label: "Video gen", blurb: "Clips, avatars, motion" },
  { id: "data", label: "Excel / BI", blurb: "Sheets, charts, analysis" },
  { id: "notes", label: "Notes / teach", blurb: "Docs, audio, study" },
  { id: "aggregator", label: "Aggregators", blurb: "Many models in one UI" },
];

/** Market map — curated for need-matching. Live scores come from BYOK compare. */
export const MARKET: Tool[] = [
  // Chat
  {
    id: "chatgpt",
    name: "ChatGPT",
    vendor: "OpenAI",
    url: "https://chatgpt.com",
    category: "chat",
    pricing: "freemium",
    bestFor: ["general chat", "writing", "agents", "multimodal"],
    notFor: ["strict offline", "lowest cost at huge volume"],
    reliability: 4,
    freeTier: true,
    liveTestable: true,
    openRouterId: "openai/gpt-4.1-mini",
    notes: "Strong default daily driver; Free/Plus tiers differ a lot.",
    tags: ["gpt", "consumer", "openai"],
  },
  {
    id: "claude",
    name: "Claude",
    vendor: "Anthropic",
    url: "https://claude.ai",
    category: "chat",
    pricing: "freemium",
    bestFor: ["long docs", "careful reasoning", "coding chat", "enterprise tone"],
    notFor: ["real-time social news"],
    reliability: 5,
    freeTier: true,
    liveTestable: true,
    openRouterId: "anthropic/claude-sonnet-4",
    notes: "Often steadiest on consistency for writing and code explanations.",
    tags: ["anthropic", "sonnet", "opus"],
  },
  {
    id: "gemini",
    name: "Gemini",
    vendor: "Google",
    url: "https://gemini.google.com",
    category: "chat",
    pricing: "freemium",
    bestFor: ["multimodal", "search grounding", "Google Workspace"],
    notFor: ["air-gapped work"],
    reliability: 4,
    freeTier: true,
    liveTestable: true,
    openRouterId: "google/gemini-2.0-flash",
    notes: "Best when you already live in Google Docs/Sheets/Drive.",
    tags: ["google", "multimodal"],
  },
  {
    id: "grok",
    name: "Grok",
    vendor: "xAI",
    url: "https://x.com/i/grok",
    category: "chat",
    pricing: "freemium",
    bestFor: ["real-time X signal", "irreverent brainstorming"],
    notFor: ["regulated enterprise defaults"],
    reliability: 3,
    freeTier: true,
    liveTestable: true,
    openRouterId: "x-ai/grok-3-mini",
    notes: "Personality-forward; check consistency before trusting for specs.",
    tags: ["xai", "grok"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    vendor: "DeepSeek",
    url: "https://chat.deepseek.com",
    category: "chat",
    pricing: "freemium",
    bestFor: ["cheap strong reasoning", "coding", "high volume"],
    notFor: ["strict US-data residency without review"],
    reliability: 4,
    freeTier: true,
    liveTestable: true,
    openRouterId: "deepseek/deepseek-chat",
    notes: "Excellent cost/capability; great Free/API testing candidate.",
    tags: ["open-weight-ish", "value"],
  },
  {
    id: "qwen",
    name: "Qwen Chat",
    vendor: "Alibaba",
    url: "https://chat.qwen.ai",
    category: "chat",
    pricing: "free",
    bestFor: ["long context", "codebases", "open-friendly workflows"],
    notFor: ["US enterprise procurement by default"],
    reliability: 4,
    freeTier: true,
    liveTestable: true,
    openRouterId: "qwen/qwen3-32b",
    notes: "Strong free chat; generous context for docs/code dumps.",
    tags: ["qwen", "free"],
  },
  {
    id: "kimi",
    name: "Kimi",
    vendor: "Moonshot",
    url: "https://kimi.com",
    category: "chat",
    pricing: "free",
    bestFor: ["long docs", "research dumps", "generous free chat"],
    notFor: ["offline"],
    reliability: 4,
    freeTier: true,
    liveTestable: true,
    openRouterId: "moonshotai/kimi-k2",
    notes: "Free tier is notably generous vs many Western chats.",
    tags: ["kimi", "long-context"],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    vendor: "Perplexity",
    url: "https://www.perplexity.ai",
    category: "chat",
    pricing: "freemium",
    bestFor: ["cited web answers", "fast research", "multi-model switch"],
    notFor: ["deep offline coding agents"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Research-first chat; free tier already switches models in-UI.",
    tags: ["search", "citations"],
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    vendor: "Meta",
    url: "https://www.meta.ai",
    category: "chat",
    pricing: "free",
    bestFor: ["casual chat", "Llama access", "social surfaces"],
    notFor: ["high-stakes compliance work"],
    reliability: 3,
    freeTier: true,
    liveTestable: true,
    openRouterId: "meta-llama/llama-4-maverick",
    notes: "Easy free entry to Meta’s models.",
    tags: ["llama", "meta"],
  },
  {
    id: "mistral-vibe",
    name: "Mistral Vibe / Le Chat",
    vendor: "Mistral",
    url: "https://chat.mistral.ai",
    category: "chat",
    pricing: "freemium",
    bestFor: ["EU-friendly", "fast chat", "open-weight ecosystem"],
    notFor: ["Apple-only workflows"],
    reliability: 4,
    freeTier: true,
    liveTestable: true,
    openRouterId: "mistralai/mistral-large",
    notes: "Le Chat rebranded toward Vibe — same product family.",
    tags: ["mistral", "eu"],
  },
  {
    id: "copilot-chat",
    name: "Microsoft Copilot",
    vendor: "Microsoft",
    url: "https://copilot.microsoft.com",
    category: "chat",
    pricing: "freemium",
    bestFor: ["Windows/Office users", "Bing-grounded answers"],
    notFor: ["non-Microsoft stacks as primary IDE"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Best if you already pay for Microsoft 365.",
    tags: ["microsoft", "office"],
  },
  {
    id: "groq",
    name: "Groq",
    vendor: "Groq",
    url: "https://groq.com",
    category: "chat",
    pricing: "freemium",
    bestFor: ["ultra-fast open-model inference", "snappy testing"],
    notFor: ["proprietary frontier-only needs"],
    reliability: 4,
    freeTier: true,
    liveTestable: true,
    openRouterId: "meta-llama/llama-3.3-70b-instruct",
    notes: "Not Grok/xAI. Speed is the product.",
    tags: ["speed", "open-models"],
  },
  {
    id: "pi",
    name: "Pi",
    vendor: "Inflection",
    url: "https://pi.ai",
    category: "chat",
    pricing: "free",
    bestFor: ["supportive conversation", "coaching tone"],
    notFor: ["hard technical compare"],
    reliability: 3,
    freeTier: true,
    liveTestable: false,
    notes: "Different job than coding/research chats.",
    tags: ["companion"],
  },
  {
    id: "duck-ai",
    name: "Duck.ai",
    vendor: "DuckDuckGo",
    url: "https://duckduckgo.com/aichat",
    category: "chat",
    pricing: "free",
    bestFor: ["privacy-minded chat", "no-account tries"],
    notFor: ["deep agent tool use"],
    reliability: 3,
    freeTier: true,
    liveTestable: false,
    notes: "Privacy wrapper over several backends.",
    tags: ["privacy"],
  },
  {
    id: "phind",
    name: "Phind",
    vendor: "Phind",
    url: "https://www.phind.com",
    category: "chat",
    pricing: "freemium",
    bestFor: ["dev Q&A", "technical search"],
    notFor: ["creative image/video"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Coding/technical questions first.",
    tags: ["dev", "search"],
  },
  {
    id: "you",
    name: "You.com",
    vendor: "You.com",
    url: "https://you.com",
    category: "chat",
    pricing: "freemium",
    bestFor: ["pick-a-model chat", "web-augmented answers"],
    notFor: ["offline"],
    reliability: 3,
    freeTier: true,
    liveTestable: false,
    notes: "Multi-model in one consumer UI.",
    tags: ["multi-model"],
  },

  // Aggregators
  {
    id: "arena",
    name: "Arena (LMArena)",
    vendor: "Arena",
    url: "https://arena.ai",
    category: "aggregator",
    pricing: "free",
    bestFor: ["blind A/B model votes", "community preference"],
    notFor: ["private enterprise prompts"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Best free way to feel pairwise quality — not reliability-over-runs.",
    tags: ["compare", "blind"],
  },
  {
    id: "poe",
    name: "Poe",
    vendor: "Quora",
    url: "https://poe.com",
    category: "aggregator",
    pricing: "freemium",
    bestFor: ["many bots one inbox", "quick model hopping"],
    notFor: ["strict data control"],
    reliability: 3,
    freeTier: true,
    liveTestable: false,
    notes: "Side-by-side access beats 20 tabs.",
    tags: ["multi-model"],
  },
  {
    id: "huggingchat",
    name: "HuggingChat",
    vendor: "Hugging Face",
    url: "https://huggingface.co/chat",
    category: "aggregator",
    pricing: "free",
    bestFor: ["open models", "no-account try", "flip between Llama/Mistral/Qwen"],
    notFor: ["SLA-backed enterprise"],
    reliability: 3,
    freeTier: true,
    liveTestable: false,
    notes: "Free open-model playground.",
    tags: ["open", "hf"],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    vendor: "OpenRouter",
    url: "https://openrouter.ai",
    category: "aggregator",
    pricing: "api",
    bestFor: ["one API key → many models", "SameAsk live tests"],
    notFor: ["people who only want a consumer chat site"],
    reliability: 4,
    freeTier: true,
    liveTestable: true,
    notes: "Best BYOK path for this product’s live compare.",
    tags: ["api", "byok"],
  },
  {
    id: "typingmind",
    name: "TypingMind",
    vendor: "TypingMind",
    url: "https://www.typingmind.com",
    category: "aggregator",
    pricing: "paid",
    bestFor: ["BYOK chat UI", "power users"],
    notFor: ["fully free forever"],
    reliability: 4,
    freeTier: false,
    liveTestable: false,
    notes: "Bring your own keys; polished multi-model client.",
    tags: ["byok", "client"],
  },
  {
    id: "librechat",
    name: "LibreChat",
    vendor: "LibreChat",
    url: "https://www.librechat.ai",
    category: "aggregator",
    pricing: "free",
    bestFor: ["self-host multi-model", "team control"],
    notFor: ["zero-setup casual users"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Open-source ChatGPT-style UI for many backends.",
    tags: ["self-host", "oss"],
  },
  {
    id: "anythingllm",
    name: "AnythingLLM",
    vendor: "Mintplex",
    url: "https://anythingllm.com",
    category: "aggregator",
    pricing: "freemium",
    bestFor: ["private docs + local/remote LLMs", "RAG workspaces"],
    notFor: ["pure image/video gen"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Doc chat with your own models.",
    tags: ["rag", "local"],
  },

  // Coding
  {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    url: "https://cursor.com",
    category: "coding",
    pricing: "freemium",
    bestFor: ["agentic coding", "multi-file edits", "repo chat"],
    notFor: ["non-dev creative video"],
    reliability: 5,
    freeTier: true,
    liveTestable: false,
    notes: "IDE-first; reliability comes from harness + model choice.",
    tags: ["ide", "agents"],
  },
  {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Codeium",
    url: "https://windsurf.com",
    category: "coding",
    pricing: "freemium",
    bestFor: ["AI IDE alternative", "cascade-style flows"],
    notFor: ["non-coding BI"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Competes in the AI editor lane with Cursor.",
    tags: ["ide"],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    vendor: "GitHub / Microsoft",
    url: "https://github.com/features/copilot",
    category: "coding",
    pricing: "paid",
    bestFor: ["inline completion", "PR help", "VS Code/JetBrains"],
    notFor: ["full autonomous multi-hour agents alone"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Best when you already live in GitHub.",
    tags: ["ide", "completion"],
  },
  {
    id: "claude-code",
    name: "Claude Code",
    vendor: "Anthropic",
    url: "https://www.anthropic.com",
    category: "coding",
    pricing: "paid",
    bestFor: ["terminal/agent coding", "careful refactors"],
    notFor: ["casual mobile chat"],
    reliability: 5,
    freeTier: false,
    liveTestable: false,
    notes: "Agent coding surface on Claude models.",
    tags: ["cli", "agents"],
  },
  {
    id: "codex",
    name: "Codex / GPT Codex",
    vendor: "OpenAI",
    url: "https://openai.com",
    category: "coding",
    pricing: "paid",
    bestFor: ["OpenAI coding agents", "repo tasks"],
    notFor: ["offline air-gap"],
    reliability: 4,
    freeTier: false,
    liveTestable: false,
    notes: "OpenAI’s coding-agent line (version names shift fast).",
    tags: ["agents", "openai"],
  },
  {
    id: "gemini-code-assist",
    name: "Gemini Code Assist",
    vendor: "Google",
    url: "https://codeassist.google",
    category: "coding",
    pricing: "freemium",
    bestFor: ["Google Cloud / Workspace devs"],
    notFor: ["Apple-only stacks"],
    reliability: 3,
    freeTier: true,
    liveTestable: false,
    notes: "Fits Google’s ecosystem.",
    tags: ["ide", "google"],
  },

  // Image
  {
    id: "chatgpt-images",
    name: "ChatGPT Images (GPT Image)",
    vendor: "OpenAI",
    url: "https://chatgpt.com",
    category: "image",
    pricing: "freemium",
    bestFor: ["chat-native images", "iterate in conversation"],
    notFor: ["print-ready brand systems alone"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Image models inside ChatGPT; names iterate (1 / 1.5 / 2).",
    tags: ["image"],
  },
  {
    id: "midjourney",
    name: "Midjourney",
    vendor: "Midjourney",
    url: "https://www.midjourney.com",
    category: "image",
    pricing: "paid",
    bestFor: ["aesthetic stills", "art direction"],
    notFor: ["free unlimited"],
    reliability: 5,
    freeTier: false,
    liveTestable: false,
    notes: "Still the taste leader for many creatives.",
    tags: ["image", "art"],
  },
  {
    id: "flux",
    name: "FLUX.2 family",
    vendor: "Black Forest Labs",
    url: "https://bfl.ai",
    category: "image",
    pricing: "api",
    bestFor: ["controllable gen", "dev pipelines"],
    notFor: ["zero-setup casual only"],
    reliability: 4,
    freeTier: false,
    liveTestable: false,
    notes: "Pro/Flex/Dev/etc. — pick by latency vs quality.",
    tags: ["image", "api"],
  },
  {
    id: "imagen",
    name: "Imagen",
    vendor: "Google",
    url: "https://deepmind.google/technologies/imagen",
    category: "image",
    pricing: "api",
    bestFor: ["Google stack images", "photoreal"],
    notFor: ["Discord-native art communities"],
    reliability: 4,
    freeTier: false,
    liveTestable: false,
    notes: "Often surfaced via Gemini / Vertex.",
    tags: ["image", "google"],
  },
  {
    id: "ideogram",
    name: "Ideogram",
    vendor: "Ideogram",
    url: "https://ideogram.ai",
    category: "image",
    pricing: "freemium",
    bestFor: ["text-in-image", "posters", "logos drafts"],
    notFor: ["long video"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Known for readable text in images.",
    tags: ["image", "text"],
  },

  // Video
  {
    id: "veo",
    name: "Veo",
    vendor: "Google",
    url: "https://deepmind.google/technologies/veo",
    category: "video",
    pricing: "paid",
    bestFor: ["high-quality short video", "Gemini ecosystem"],
    notFor: ["free unlimited"],
    reliability: 4,
    freeTier: false,
    liveTestable: false,
    notes: "Veo 3.x line — quality-first Google video.",
    tags: ["video"],
  },
  {
    id: "runway",
    name: "Runway",
    vendor: "Runway",
    url: "https://runwayml.com",
    category: "video",
    pricing: "paid",
    bestFor: ["creator video tools", "gen + edit"],
    notFor: ["spreadsheet BI"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Gen-3/4 family; strong creative suite.",
    tags: ["video"],
  },
  {
    id: "kling",
    name: "Kling",
    vendor: "Kuaishou",
    url: "https://klingai.com",
    category: "video",
    pricing: "freemium",
    bestFor: ["cinematic clips", "value video gen"],
    notFor: ["enterprise SSO by default"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Fast-moving 2.x/3.x releases.",
    tags: ["video"],
  },
  {
    id: "luma",
    name: "Luma Dream Machine / Ray",
    vendor: "Luma",
    url: "https://lumalabs.ai",
    category: "video",
    pricing: "freemium",
    bestFor: ["dreamy motion", "quick concept clips"],
    notFor: ["avatar corporate training alone"],
    reliability: 3,
    freeTier: true,
    liveTestable: false,
    notes: "Ray line for next-gen motion.",
    tags: ["video"],
  },
  {
    id: "heygen",
    name: "HeyGen",
    vendor: "HeyGen",
    url: "https://www.heygen.com",
    category: "video",
    pricing: "paid",
    bestFor: ["talking-head avatars", "training videos"],
    notFor: ["abstract art film"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Avatar/talking-head specialist.",
    tags: ["avatar", "video"],
  },

  // Data
  {
    id: "chatgpt-excel",
    name: "ChatGPT for Excel / Advanced Data Analysis",
    vendor: "OpenAI",
    url: "https://chatgpt.com",
    category: "data",
    pricing: "freemium",
    bestFor: ["upload-and-analyze", "Python-backed EDA"],
    notFor: ["live governed warehouse without setup"],
    reliability: 4,
    freeTier: false,
    liveTestable: false,
    notes: "Code Interpreter style analysis in chat.",
    tags: ["excel", "analysis"],
  },
  {
    id: "copilot-excel",
    name: "Copilot in Excel",
    vendor: "Microsoft",
    url: "https://www.microsoft.com/microsoft-365/excel",
    category: "data",
    pricing: "paid",
    bestFor: ["formulas", "Office-native sheets"],
    notFor: ["Google Sheets users"],
    reliability: 4,
    freeTier: false,
    liveTestable: false,
    notes: "Best inside Microsoft 365.",
    tags: ["excel", "office"],
  },
  {
    id: "gemini-sheets",
    name: "Gemini in Google Sheets",
    vendor: "Google",
    url: "https://sheets.google.com",
    category: "data",
    pricing: "freemium",
    bestFor: ["Sheets natives", "quick clean/fill"],
    notFor: ["Excel-only shops"],
    reliability: 3,
    freeTier: true,
    liveTestable: false,
    notes: "Workspace-integrated help.",
    tags: ["sheets"],
  },
  {
    id: "julius",
    name: "Julius AI",
    vendor: "Julius",
    url: "https://julius.ai",
    category: "data",
    pricing: "freemium",
    bestFor: ["chat with spreadsheets/CSVs", "plots"],
    notFor: ["full BI governance"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Analyst-friendly data chat.",
    tags: ["csv", "plots"],
  },
  {
    id: "powerbi-copilot",
    name: "Power BI + Copilot",
    vendor: "Microsoft",
    url: "https://powerbi.microsoft.com",
    category: "data",
    pricing: "paid",
    bestFor: ["enterprise dashboards", "governed metrics"],
    notFor: ["one-off homework CSVs"],
    reliability: 4,
    freeTier: false,
    liveTestable: false,
    notes: "BI layer, not a general chat model.",
    tags: ["bi"],
  },

  // Notes / teach
  {
    id: "notebooklm",
    name: "NotebookLM",
    vendor: "Google",
    url: "https://notebooklm.google.com",
    category: "notes",
    pricing: "free",
    bestFor: ["grounded study on YOUR docs", "audio overviews"],
    notFor: ["open-world unconstrained chat"],
    reliability: 5,
    freeTier: true,
    liveTestable: false,
    notes: "Different job: sources-first Q&A and teaching.",
    tags: ["docs", "study"],
  },
  {
    id: "claude-cowork",
    name: "Claude Cowork / Artifacts-style work",
    vendor: "Anthropic",
    url: "https://claude.ai",
    category: "notes",
    pricing: "freemium",
    bestFor: ["docs + iterative artifacts", "team writing"],
    notFor: ["video generation"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Doc/work surfaces on Claude.",
    tags: ["docs"],
  },
  {
    id: "chatgpt-canvas",
    name: "ChatGPT Canvas",
    vendor: "OpenAI",
    url: "https://chatgpt.com",
    category: "notes",
    pricing: "freemium",
    bestFor: ["co-editing writing/code canvases"],
    notFor: ["source-grounded classroom only"],
    reliability: 4,
    freeTier: true,
    liveTestable: false,
    notes: "Side canvas for longer drafting.",
    tags: ["docs", "canvas"],
  },
];

export function getTool(id: string): Tool | undefined {
  return MARKET.find((t) => t.id === id);
}
